contact_links:
- name: ğŸ“ï¸â€‚ Learn More
  about: Not sure where to start? Read our contribution guide to learn more.
  url: https://DrugBud-Suite.github.io/VoteM8/contribute
- name: ğŸ’¬â€‚ Contact Us
  about: Have another inquiry or need help? Contact us directly!
  url: https://DrugBud-Suite.github.io/VoteM8/about/contact
